DROP SCHEMA IF EXISTS Epers_DB;
CREATE SCHEMA Epers_DB;

USE Epers_DB;

CREATE TABLE `Epers_DB`.`USUARIO` (
  `NOMBRE` VARCHAR(30)  NOT NULL,
  `APELLIDO` VARCHAR(30) NOT NULL,
  `NOMBREUSUARIO` VARCHAR(30) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(30) NOT NULL,
  `EMAIL` VARCHAR(30) NOT NULL,
  `FECHADENACIMIENTO` VARCHAR(30) NOT NULL,
  `VALIDADO` TINYINT(1) NOT NULL, 
  PRIMARY KEY (`NOMBREUSUARIO`)
)
ENGINE = InnoDB;

CREATE TABLE `Epers_DB`.`USUARIO_CODIGO` (
  `NOMBREUSUARIO` VARCHAR(30) UNIQUE,
  `CODIGO` VARCHAR(40) NOT NULL,
   PRIMARY KEY ('NOMBREUSUARIO'),
   FOREIGN KEY ('NOMBREUSUARIO') REFERENCES 'USUARIO'('NOMBREUSUARIO')
)
ENGINE = InnoDB;


